sudo: required

matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          language: generic
        - env: DOCKER=true OS_TYPE=centos OS_VERSION=centos7
        - env: DOCKER=true OS_TYPE=ubuntu OS_VERSION=xenial
        - env: DOCKER=true OS_TYPE=ubuntu OS_VERSION=bionic
    allow_failures:
        - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./dependencies_osx.sh          ; fi
    - if [[ "$DOCKER" == "true" ]]; then docker pull ${OS_TYPE}:${OS_VERSION}  ; fi

script:
     - if [[ "$DOCKER" == "true" ]] && [[ "$OS_TYPE" == "centos" ]]; then docker run -v `pwd`:/ydk-go ${OS_TYPE}:${OS_VERSION} bash -c "cd /ydk-go && ./dependencies_centos.sh && ./tests.sh" ; fi
     - if [[ "$DOCKER" == "true" ]] && [[ "$OS_TYPE" == "ubuntu" ]]; then docker run -v `pwd`:/ydk-go ${OS_TYPE}:${OS_VERSION} bash -c "cd /ydk-go && ./dependencies_xenial.sh && ./tests.sh" ; fi
     - if [[ "$DOCKER" != "true" ]]; then ./tests.sh ; fi
