// This module manages Cisco's intercept feature.
// This MIB replaces CISCO-TAP-MIB. This MIB defines
// a generic stream table that contains fields common to
// all intercept types. Specific intercept filters are
// defined in extension MIBs. They are CISCO-IP-TAP-MIB
// for IP intercepts, CISCO-802-TAP-MIB for IEEE 802
// intercepts and CISCO-USER-CONNECTION-TAP-MIB for
// RADIUS-based user connection intercepts.
package cisco_tap2_mib

import (
    "fmt"
    "github.com/CiscoDevNet/ydk-go/ydk"
    "github.com/CiscoDevNet/ydk-go/ydk/types"
    "github.com/CiscoDevNet/ydk-go/ydk/types/yfilter"
    "github.com/CiscoDevNet/ydk-go/ydk/models/cisco_ios_xe"
    "reflect"
)

func init() {
    ydk.YLogDebug(fmt.Sprintf("Registering top level entities for package cisco_tap2_mib"))
    ydk.RegisterEntity("{urn:ietf:params:xml:ns:yang:smiv2:CISCO-TAP2-MIB CISCO-TAP2-MIB}", reflect.TypeOf(CISCOTAP2MIB{}))
    ydk.RegisterEntity("CISCO-TAP2-MIB:CISCO-TAP2-MIB", reflect.TypeOf(CISCOTAP2MIB{}))
}

// CISCOTAP2MIB
type CISCOTAP2MIB struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    
    Ctap2Mediationgroup CISCOTAP2MIB_Ctap2Mediationgroup

    
    Ctap2Debuggroup CISCOTAP2MIB_Ctap2Debuggroup

    // This table lists the Mediation Devices with which the intercepting device
    // communicates. These may be on the same or different Mediation Devices.  
    // This table is written by the Mediation Device, and is always volatile. This
    // is because intercepts may disappear during a restart of the intercepting
    // equipment.  Entries are added to this table via cTap2MediationStatus in 
    // accordance with the RowStatus convention.
    Ctap2Mediationtable CISCOTAP2MIB_Ctap2Mediationtable

    // The Intercept Stream Table lists the traffic streams to be intercepted. The
    // same data stream may be required by multiple  taps, and one might assume
    // that often the intercepted stream  is a small subset of the traffic that
    // could be intercepted.   The Table consists of generic fields that are
    // independent of the type of intercept. It contains type of the specific 
    // filter which is defined in an extension MIB and counters to  account for
    // packets intercepted or dropped by the attached filter specification.  Note
    // that the Mediation Device must make sure there is  only one type of
    // specific filter created with the same  indices as that of a row in this
    // table, otherwise the  later creations will fail. For example, if there is a
    // row in this table with index 1.2, there can be a  corresponding row with
    // the same index either in  citapStreamTable, c8tapStreamTable or
    // cuctTapStreamTable, but not all.    The first index indicates which
    // Mediation Device the intercepted traffic will be diverted to. The second
    // index permits multiple classifiers to be used together.   Entries are added
    // to this table via cTap2StreamStatus in accordance with the RowStatus
    // convention.
    Ctap2Streamtable CISCOTAP2MIB_Ctap2Streamtable

    // A table that contains Lawful Intercept debug messages generated by the
    // implementing device. This table is used  by ciscoTap2MediationDebug and
    // ciscoTap2StreamDebug  notifications.  An entry in this table contains a
    // debug message which is regarding either a Mediation Device or a intercept
    // stream  created by a Mediation Device. The Mediation device is  identified
    // by cTap2DebugMediationId whose value is that of cTap2MediationContentId of
    // cTapMediationEntry. The stream is identified by cTap2DebugMediationId and
    // cTap2DebugStreamId whose values are that of  cTap2MediationContentId and
    // cTap2StreamIndex of  the corresponding cTap2StreamEntry.  Note that
    // cTap2DebugStreamId may be zero for an entry, in which case the debug
    // message is regarding a Medation Device.  Entries are added to this table
    // via cTap2DebugStatus in accordance with the RowStatus convention.
    Ctap2Debugtable CISCOTAP2MIB_Ctap2Debugtable

    // The User Table lists information of all the users configured in the system
    // who are given permission by different Mediation Devices to access Lawful
    // Intercept CLIs.  This table will have dependancy on cTap2MediationTable.
    // When entry in cTap2MediationTable is deleted or moved to 'notInService',
    // entries corresponding cTap2MediationContentId in this table will be
    // deleted.
    Ctap2Debugusertable CISCOTAP2MIB_Ctap2Debugusertable
}

func (cISCOTAP2MIB *CISCOTAP2MIB) GetEntityData() *types.CommonEntityData {
    cISCOTAP2MIB.EntityData.YFilter = cISCOTAP2MIB.YFilter
    cISCOTAP2MIB.EntityData.YangName = "CISCO-TAP2-MIB"
    cISCOTAP2MIB.EntityData.BundleName = "cisco_ios_xe"
    cISCOTAP2MIB.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    cISCOTAP2MIB.EntityData.SegmentPath = "CISCO-TAP2-MIB:CISCO-TAP2-MIB"
    cISCOTAP2MIB.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    cISCOTAP2MIB.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    cISCOTAP2MIB.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    cISCOTAP2MIB.EntityData.Children = make(map[string]types.YChild)
    cISCOTAP2MIB.EntityData.Children["cTap2MediationGroup"] = types.YChild{"Ctap2Mediationgroup", &cISCOTAP2MIB.Ctap2Mediationgroup}
    cISCOTAP2MIB.EntityData.Children["cTap2DebugGroup"] = types.YChild{"Ctap2Debuggroup", &cISCOTAP2MIB.Ctap2Debuggroup}
    cISCOTAP2MIB.EntityData.Children["cTap2MediationTable"] = types.YChild{"Ctap2Mediationtable", &cISCOTAP2MIB.Ctap2Mediationtable}
    cISCOTAP2MIB.EntityData.Children["cTap2StreamTable"] = types.YChild{"Ctap2Streamtable", &cISCOTAP2MIB.Ctap2Streamtable}
    cISCOTAP2MIB.EntityData.Children["cTap2DebugTable"] = types.YChild{"Ctap2Debugtable", &cISCOTAP2MIB.Ctap2Debugtable}
    cISCOTAP2MIB.EntityData.Children["cTap2DebugUserTable"] = types.YChild{"Ctap2Debugusertable", &cISCOTAP2MIB.Ctap2Debugusertable}
    cISCOTAP2MIB.EntityData.Leafs = make(map[string]types.YLeaf)
    return &(cISCOTAP2MIB.EntityData)
}

// CISCOTAP2MIB_Ctap2Mediationgroup
type CISCOTAP2MIB_Ctap2Mediationgroup struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // This object contains a value which may be used as an index value for a new
    // cTap2MediationEntry. Whenever read, the agent will change the value to a
    // new non-conflicting value.  This is to reduce the probability of errors
    // during creation of new cTap2MediationTable entries. The type is interface{}
    // with range: 1..2147483647.
    Ctap2Mediationnewindex interface{}

    // This object displays the device capabilities with respect to certain fields
    // in Mediation Device table. This may be dependent on hardware capabilities,
    // software capabilities. The following values may be supported:    
    // ipV4SrcInterface:  SNMP ifIndex Value may be used to select                
    // the interface (denoted by                       
    // cTap2MediationSrcInterface) on the                        intercepting
    // device from which to                        transmit intercepted data to an
    // IPv4                        address Mediation Device.      
    // ipV6SrcInterface:  SNMP ifIndex Value may be used to select                
    // the interface (denoted by                       
    // cTap2MediationSrcInterface) on the                        intercepting
    // device from which to                        transmit intercepted data to an
    // IPv6                        address Mediation Device.       udp:           
    // UDP may be used as transport protocol                        (denoted by
    // cTap2MediationTransport) in                        transferring intercepted
    // data to the                        Mediation Device.       rtcpNack:       
    // RTP with Nack resilience may be used                        as transport
    // protocol (denoted by                        cTap2MediationTransport) in
    // transferring                        intercepted data to the Mediation      
    // Device.      tcp:               TCP may be used as transport protocol      
    // (denoted by cTap2MediationTransport) in                        transferring
    // intercepted data to the                        Mediation Device.      
    // sctp:              SCTP may be used as transport protocol                  
    // (denoted by cTap2MediationTransport) in                        transferring
    // intercepted data to the                        Mediation Device.      rtp: 
    // RTP may be used as transport protocol                        (denoted by
    // cTap2MediationTransport) in                        transferring intercepted
    // data to the                        Mediation Device.       radius:         
    // Radius may be used as transport protocol                        (denoted by
    // cTap2MediationTransport) in                        transferring intercepted
    // information to                         the Mediation Device. The type is
    // map[string]bool.
    Ctap2Mediationcapabilities interface{}
}

func (ctap2Mediationgroup *CISCOTAP2MIB_Ctap2Mediationgroup) GetEntityData() *types.CommonEntityData {
    ctap2Mediationgroup.EntityData.YFilter = ctap2Mediationgroup.YFilter
    ctap2Mediationgroup.EntityData.YangName = "cTap2MediationGroup"
    ctap2Mediationgroup.EntityData.BundleName = "cisco_ios_xe"
    ctap2Mediationgroup.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    ctap2Mediationgroup.EntityData.SegmentPath = "cTap2MediationGroup"
    ctap2Mediationgroup.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Mediationgroup.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Mediationgroup.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Mediationgroup.EntityData.Children = make(map[string]types.YChild)
    ctap2Mediationgroup.EntityData.Leafs = make(map[string]types.YLeaf)
    ctap2Mediationgroup.EntityData.Leafs["cTap2MediationNewIndex"] = types.YLeaf{"Ctap2Mediationnewindex", ctap2Mediationgroup.Ctap2Mediationnewindex}
    ctap2Mediationgroup.EntityData.Leafs["cTap2MediationCapabilities"] = types.YLeaf{"Ctap2Mediationcapabilities", ctap2Mediationgroup.Ctap2Mediationcapabilities}
    return &(ctap2Mediationgroup.EntityData)
}

// CISCOTAP2MIB_Ctap2Debuggroup
type CISCOTAP2MIB_Ctap2Debuggroup struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // This object contains the duration in minutes for which an entry in
    // cTap2DebugTable is maintained by the implementing device after which the
    // entry is deleted. The management station also has the option of deleting
    // the entry itself by setting cTap2DebugStatus. The type is interface{} with
    // range: 1..2147483647.
    Ctap2Debugage interface{}

    // This object contains the maximum number of debug messages maintained by the
    // implementing device at a time. If this  limit is crossed, most recent
    // message will replace the least recent message. The type is interface{} with
    // range: 1..2147483647.
    Ctap2Debugmaxentries interface{}
}

func (ctap2Debuggroup *CISCOTAP2MIB_Ctap2Debuggroup) GetEntityData() *types.CommonEntityData {
    ctap2Debuggroup.EntityData.YFilter = ctap2Debuggroup.YFilter
    ctap2Debuggroup.EntityData.YangName = "cTap2DebugGroup"
    ctap2Debuggroup.EntityData.BundleName = "cisco_ios_xe"
    ctap2Debuggroup.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    ctap2Debuggroup.EntityData.SegmentPath = "cTap2DebugGroup"
    ctap2Debuggroup.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Debuggroup.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Debuggroup.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Debuggroup.EntityData.Children = make(map[string]types.YChild)
    ctap2Debuggroup.EntityData.Leafs = make(map[string]types.YLeaf)
    ctap2Debuggroup.EntityData.Leafs["cTap2DebugAge"] = types.YLeaf{"Ctap2Debugage", ctap2Debuggroup.Ctap2Debugage}
    ctap2Debuggroup.EntityData.Leafs["cTap2DebugMaxEntries"] = types.YLeaf{"Ctap2Debugmaxentries", ctap2Debuggroup.Ctap2Debugmaxentries}
    return &(ctap2Debuggroup.EntityData)
}

// CISCOTAP2MIB_Ctap2Mediationtable
// This table lists the Mediation Devices with which the
// intercepting device communicates. These may be on the same or
// different Mediation Devices.
// 
// 
// This table is written by the Mediation Device, and is always
// volatile. This is because intercepts may disappear during a
// restart of the intercepting equipment.
// 
// Entries are added to this table via cTap2MediationStatus in 
// accordance with the RowStatus convention.
type CISCOTAP2MIB_Ctap2Mediationtable struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // The entry describes a single session maintained with an application on a
    // Mediation Device. The type is slice of
    // CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry.
    Ctap2Mediationentry []CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry
}

func (ctap2Mediationtable *CISCOTAP2MIB_Ctap2Mediationtable) GetEntityData() *types.CommonEntityData {
    ctap2Mediationtable.EntityData.YFilter = ctap2Mediationtable.YFilter
    ctap2Mediationtable.EntityData.YangName = "cTap2MediationTable"
    ctap2Mediationtable.EntityData.BundleName = "cisco_ios_xe"
    ctap2Mediationtable.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    ctap2Mediationtable.EntityData.SegmentPath = "cTap2MediationTable"
    ctap2Mediationtable.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Mediationtable.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Mediationtable.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Mediationtable.EntityData.Children = make(map[string]types.YChild)
    ctap2Mediationtable.EntityData.Children["cTap2MediationEntry"] = types.YChild{"Ctap2Mediationentry", nil}
    for i := range ctap2Mediationtable.Ctap2Mediationentry {
        ctap2Mediationtable.EntityData.Children[types.GetSegmentPath(&ctap2Mediationtable.Ctap2Mediationentry[i])] = types.YChild{"Ctap2Mediationentry", &ctap2Mediationtable.Ctap2Mediationentry[i]}
    }
    ctap2Mediationtable.EntityData.Leafs = make(map[string]types.YLeaf)
    return &(ctap2Mediationtable.EntityData)
}

// CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry
// The entry describes a single session maintained with an
// application on a Mediation Device.
type CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // This attribute is a key. cTap2MediationContentId is a session identifier,
    // from the intercept application's perspective, and a content identifier from
    // the Mediation Device's perspective. The Mediation Device is responsible for
    // making sure these are unique, although the SNMP RowStatus row creation
    // process will help by not allowing it to create conflicting entries. Before
    // creating a new entry, a value for this variable may be obtained by reading
    // cTap2MediationNewIndex to reduce the probability of a value collision. The
    // type is interface{} with range: 1..2147483647.
    Ctap2Mediationcontentid interface{}

    // The type of cTap2MediationDestAddress. The type is InetAddressType.
    Ctap2Mediationdestaddresstype interface{}

    // The IP Address of the Mediation Device's network interface to which to
    // direct intercepted traffic. The type is string with length: 0..255.
    Ctap2Mediationdestaddress interface{}

    // The port number on the Mediation Device's network interface to which to
    // direct intercepted traffic. The type is interface{} with range: 0..65535.
    Ctap2Mediationdestport interface{}

    // The interface on the intercepting device from which to transmit intercepted
    // data. If zero, any interface may be used according to normal IP practice.
    // The type is interface{} with range: 0..2147483647.
    Ctap2Mediationsrcinterface interface{}

    // The port number on the intercepting device to which the Mediation Devices
    // directs RTCP Receiver Reports and Nacks. This object is only relevant when
    // the value of cTap2MediationTransport is 'rtpNack'.   This port is assigned
    // by the intercepting device, rather than by the Mediation Device or manager
    // application.  The value of this MIB object has no effect before activating
    // the cTap2MediationEntry. The type is interface{} with range: 0..65535.
    Ctap2Mediationrtcpport interface{}

    // The Differentiated Services Code Point the intercepting device applies to
    // the IP packets encapsulating the intercepted traffic. The type is
    // interface{} with range: 0..63.
    Ctap2Mediationdscp interface{}

    // If RTP with Ack/Nack resilience is selected as a transport, the mediation
    // process requires an RTP payload type for data transmissions, and a second
    // RTP payload type for retransmissions.  This is the RTP payload type for
    // transmissions.   This object is only effective when the value of
    // cTap2MediationTransport is 'rtpNack'. The type is interface{} with range:
    // 0..127.
    Ctap2Mediationdatatype interface{}

    // If RTP with Ack/Nack resilience is selected as a transport, the mediation
    // process requires an RTP payload type for data transmissions, and a second
    // RTP payload type for retransmissions.  This is the RTP payload type for
    // retransmissions.   This object is only effective when the value of
    // cTap2MediationTransport is 'rtpNack'. The type is interface{} with range:
    // 0..127.
    Ctap2Mediationretransmittype interface{}

    // The time at which this row and all related Stream Table rows should be
    // automatically removed, and the intercept function cease. Since the
    // initiating network manager may be the only device able to manage a specific
    // intercept or know of its existence, this acts as a fail-safe for the
    // failure or removal of the network manager. The object is only effective
    // when the value of cTap2MediationStatus is 'active'. The type is string.
    Ctap2Mediationtimeout interface{}

    // The protocol used in transferring intercepted data to the Mediation Device.
    // The following protocols may be supported:            udp:     PacketCable
    // udp format            rtpNack: RTP with Nack resilience            tcp:    
    // TCP with head of line blocking            sctp:    SCTP with head of line
    // blocking             rtp:     Realtime Transport Protocol(RTP)             
    // packet format            radius:  Use Radius, PacketCable1.5 Event Message 
    // to transport the intercepted information. The type is
    // Ctap2Mediationtransport.
    Ctap2Mediationtransport interface{}

    // This variable controls the generation of any notifications or informs by
    // the MIB agent for this table entry. The type is bool.
    Ctap2Mediationnotificationenable interface{}

    // The status of this conceptual row. This object is used to manage creation,
    // modification and deletion of rows in this table.   cTap2MediationTimeout
    // may be modified at any time (even while the row is active). But when the
    // row is active, the other writable objects may not be modified without
    // setting its value to 'notInService'.   The entry may not be deleted or
    // deactivated by setting its value to 'destroy' or 'notInService' if there is
    // any associated entry in cTap2StreamTable. The type is RowStatus.
    Ctap2Mediationstatus interface{}

    // Radius Authentication Key is the shared secret key between  radius client
    // and server. The type is string with length: 0..64.
    Ctap2Mediationradiuskey interface{}
}

func (ctap2Mediationentry *CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry) GetEntityData() *types.CommonEntityData {
    ctap2Mediationentry.EntityData.YFilter = ctap2Mediationentry.YFilter
    ctap2Mediationentry.EntityData.YangName = "cTap2MediationEntry"
    ctap2Mediationentry.EntityData.BundleName = "cisco_ios_xe"
    ctap2Mediationentry.EntityData.ParentYangName = "cTap2MediationTable"
    ctap2Mediationentry.EntityData.SegmentPath = "cTap2MediationEntry" + "[cTap2MediationContentId='" + fmt.Sprintf("%v", ctap2Mediationentry.Ctap2Mediationcontentid) + "']"
    ctap2Mediationentry.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Mediationentry.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Mediationentry.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Mediationentry.EntityData.Children = make(map[string]types.YChild)
    ctap2Mediationentry.EntityData.Leafs = make(map[string]types.YLeaf)
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationContentId"] = types.YLeaf{"Ctap2Mediationcontentid", ctap2Mediationentry.Ctap2Mediationcontentid}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationDestAddressType"] = types.YLeaf{"Ctap2Mediationdestaddresstype", ctap2Mediationentry.Ctap2Mediationdestaddresstype}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationDestAddress"] = types.YLeaf{"Ctap2Mediationdestaddress", ctap2Mediationentry.Ctap2Mediationdestaddress}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationDestPort"] = types.YLeaf{"Ctap2Mediationdestport", ctap2Mediationentry.Ctap2Mediationdestport}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationSrcInterface"] = types.YLeaf{"Ctap2Mediationsrcinterface", ctap2Mediationentry.Ctap2Mediationsrcinterface}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationRtcpPort"] = types.YLeaf{"Ctap2Mediationrtcpport", ctap2Mediationentry.Ctap2Mediationrtcpport}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationDscp"] = types.YLeaf{"Ctap2Mediationdscp", ctap2Mediationentry.Ctap2Mediationdscp}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationDataType"] = types.YLeaf{"Ctap2Mediationdatatype", ctap2Mediationentry.Ctap2Mediationdatatype}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationRetransmitType"] = types.YLeaf{"Ctap2Mediationretransmittype", ctap2Mediationentry.Ctap2Mediationretransmittype}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationTimeout"] = types.YLeaf{"Ctap2Mediationtimeout", ctap2Mediationentry.Ctap2Mediationtimeout}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationTransport"] = types.YLeaf{"Ctap2Mediationtransport", ctap2Mediationentry.Ctap2Mediationtransport}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationNotificationEnable"] = types.YLeaf{"Ctap2Mediationnotificationenable", ctap2Mediationentry.Ctap2Mediationnotificationenable}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationStatus"] = types.YLeaf{"Ctap2Mediationstatus", ctap2Mediationentry.Ctap2Mediationstatus}
    ctap2Mediationentry.EntityData.Leafs["cTap2MediationRadiusKey"] = types.YLeaf{"Ctap2Mediationradiuskey", ctap2Mediationentry.Ctap2Mediationradiuskey}
    return &(ctap2Mediationentry.EntityData)
}

// CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport represents                     to transport the intercepted information.
type CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport string

const (
    CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport_udp CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport = "udp"

    CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport_rtpNack CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport = "rtpNack"

    CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport_tcp CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport = "tcp"

    CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport_sctp CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport = "sctp"

    CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport_rtp CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport = "rtp"

    CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport_radius CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationtransport = "radius"
)

// CISCOTAP2MIB_Ctap2Streamtable
// The Intercept Stream Table lists the traffic streams to be
// intercepted. The same data stream may be required by multiple 
// taps, and one might assume that often the intercepted stream 
// is a small subset of the traffic that could be intercepted.
// 
// 
// The Table consists of generic fields that are independent
// of the type of intercept. It contains type of the specific 
// filter which is defined in an extension MIB and counters to 
// account for packets intercepted or dropped by the attached
// filter specification.
// 
// Note that the Mediation Device must make sure there is 
// only one type of specific filter created with the same 
// indices as that of a row in this table, otherwise the 
// later creations will fail. For example, if there is a 
// row in this table with index 1.2, there can be a 
// corresponding row with the same index either in 
// citapStreamTable, c8tapStreamTable or cuctTapStreamTable,
// but not all. 
// 
// 
// The first index indicates which Mediation Device the
// intercepted traffic will be diverted to. The second index
// permits multiple classifiers to be used together. 
// 
// Entries are added to this table via cTap2StreamStatus in
// accordance with the RowStatus convention.
type CISCOTAP2MIB_Ctap2Streamtable struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // A stream entry indicates a single data stream to be intercepted to a
    // Mediation Device. Many selected data streams may go to the same application
    // interface, and many application interfaces are supported. The type is slice
    // of CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry.
    Ctap2Streamentry []CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry
}

func (ctap2Streamtable *CISCOTAP2MIB_Ctap2Streamtable) GetEntityData() *types.CommonEntityData {
    ctap2Streamtable.EntityData.YFilter = ctap2Streamtable.YFilter
    ctap2Streamtable.EntityData.YangName = "cTap2StreamTable"
    ctap2Streamtable.EntityData.BundleName = "cisco_ios_xe"
    ctap2Streamtable.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    ctap2Streamtable.EntityData.SegmentPath = "cTap2StreamTable"
    ctap2Streamtable.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Streamtable.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Streamtable.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Streamtable.EntityData.Children = make(map[string]types.YChild)
    ctap2Streamtable.EntityData.Children["cTap2StreamEntry"] = types.YChild{"Ctap2Streamentry", nil}
    for i := range ctap2Streamtable.Ctap2Streamentry {
        ctap2Streamtable.EntityData.Children[types.GetSegmentPath(&ctap2Streamtable.Ctap2Streamentry[i])] = types.YChild{"Ctap2Streamentry", &ctap2Streamtable.Ctap2Streamentry[i]}
    }
    ctap2Streamtable.EntityData.Leafs = make(map[string]types.YLeaf)
    return &(ctap2Streamtable.EntityData)
}

// CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry
// A stream entry indicates a single data stream to be
// intercepted to a Mediation Device. Many selected data
// streams may go to the same application interface, and many
// application interfaces are supported.
type CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // This attribute is a key. The type is string with range: 1..2147483647.
    // Refers to
    // cisco_tap2_mib.CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationcontentid
    Ctap2Mediationcontentid interface{}

    // This attribute is a key. The index of the stream itself. The type is
    // interface{} with range: 1..2147483647.
    Ctap2Streamindex interface{}

    // Identifies the type of intercept filter associated to this generic stream.
    // The following types of streams are supported:        ip:             The
    // specific filter is an IP filter                         with same indices
    // as that of this                         table. The exact filter is a row in
    // citapStreamTable of CISCO-IP-TAP-MIB.        mac:            The specific
    // filter is a MAC filter                        with same indices as that of
    // this table.                        The exact filter is a row in            
    // c8tapStreamTable of CISCO-802-TAP-MIB.        userConnecton:  The specific
    // filter is a user connection                        filter with same indices
    // as that of                         this table. The exact filter is a row   
    // in cuctTapStreamTable of                        
    // CISCO-USER-CONNECTION-TAP-MIB.        msPdsn:         The specific filter
    // is a Mobile Sub                        connection filter with same indices
    // as                        that of this table. The exact filter             
    // is a row in ccptapStreamTable of                        
    // CISCO-CDMA-PDSN-TAP-MIB.        mobility:       The specific filter is a
    // Mobile                         Subscriber connection filter with same      
    // indices as that of this table. The exact                        filter is a
    // row in cmtapStreamTable of                         CISCO-MOBILITY-TAP-MIB. 
    // voip:           The specific filter is a VoIP                       
    // Subscriber filter with same                        indices as that of this
    // table. The exact                        filter is a row in
    // cvoiptapStreamTable of                        CISCO-VOIP-TAP-MIB. The type
    // is Ctap2Streamtype.
    Ctap2Streamtype interface{}

    // If 'true', the tap should intercept matching traffic. The value for this
    // object should be set to 'true' only after an  additional filter
    // specification has been attached to this  stream. The type is bool.
    Ctap2Streaminterceptenable interface{}

    // The number of packets matching this data stream specification that have
    // been intercepted. The type is interface{} with range: 0..4294967295.
    Ctap2Streaminterceptedpackets interface{}

    // The number of packets matching this data stream specification that, having
    // been intercepted, were dropped in the lawful intercept process. The type is
    // interface{} with range: 0..4294967295.
    Ctap2Streaminterceptdrops interface{}

    // The status of this conceptual row. This object manages creation,
    // modification, and deletion of rows in this table.
    // cTap2StreamInterceptEnable may be modified any time even the value of this
    // entry rowStatus object is 'active'.  When other rows must be changed,
    // cTap2StreamStatus must be first set to 'notInService'. The type is
    // RowStatus.
    Ctap2Streamstatus interface{}

    // The number of packets matching this data stream specification that have
    // been intercepted. This object is a 64-bit version of
    // cTap2StreamInterceptedPackets. The type is interface{} with range:
    // 0..18446744073709551615.
    Ctap2Streaminterceptedhcpackets interface{}

    // The number of packets matching this data stream specification that, having
    // been intercepted, were dropped in the lawful intercept process. This object
    // is a 64-bit version of cTap2StreamInterceptDrops. The type is interface{}
    // with range: 0..18446744073709551615.
    Ctap2Streamintercepthcdrops interface{}
}

func (ctap2Streamentry *CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry) GetEntityData() *types.CommonEntityData {
    ctap2Streamentry.EntityData.YFilter = ctap2Streamentry.YFilter
    ctap2Streamentry.EntityData.YangName = "cTap2StreamEntry"
    ctap2Streamentry.EntityData.BundleName = "cisco_ios_xe"
    ctap2Streamentry.EntityData.ParentYangName = "cTap2StreamTable"
    ctap2Streamentry.EntityData.SegmentPath = "cTap2StreamEntry" + "[cTap2MediationContentId='" + fmt.Sprintf("%v", ctap2Streamentry.Ctap2Mediationcontentid) + "']" + "[cTap2StreamIndex='" + fmt.Sprintf("%v", ctap2Streamentry.Ctap2Streamindex) + "']"
    ctap2Streamentry.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Streamentry.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Streamentry.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Streamentry.EntityData.Children = make(map[string]types.YChild)
    ctap2Streamentry.EntityData.Leafs = make(map[string]types.YLeaf)
    ctap2Streamentry.EntityData.Leafs["cTap2MediationContentId"] = types.YLeaf{"Ctap2Mediationcontentid", ctap2Streamentry.Ctap2Mediationcontentid}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamIndex"] = types.YLeaf{"Ctap2Streamindex", ctap2Streamentry.Ctap2Streamindex}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamType"] = types.YLeaf{"Ctap2Streamtype", ctap2Streamentry.Ctap2Streamtype}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamInterceptEnable"] = types.YLeaf{"Ctap2Streaminterceptenable", ctap2Streamentry.Ctap2Streaminterceptenable}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamInterceptedPackets"] = types.YLeaf{"Ctap2Streaminterceptedpackets", ctap2Streamentry.Ctap2Streaminterceptedpackets}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamInterceptDrops"] = types.YLeaf{"Ctap2Streaminterceptdrops", ctap2Streamentry.Ctap2Streaminterceptdrops}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamStatus"] = types.YLeaf{"Ctap2Streamstatus", ctap2Streamentry.Ctap2Streamstatus}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamInterceptedHCPackets"] = types.YLeaf{"Ctap2Streaminterceptedhcpackets", ctap2Streamentry.Ctap2Streaminterceptedhcpackets}
    ctap2Streamentry.EntityData.Leafs["cTap2StreamInterceptHCDrops"] = types.YLeaf{"Ctap2Streamintercepthcdrops", ctap2Streamentry.Ctap2Streamintercepthcdrops}
    return &(ctap2Streamentry.EntityData)
}

// CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype represents                        CISCO-VOIP-TAP-MIB.
type CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype string

const (
    CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype_ip CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype = "ip"

    CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype_mac CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype = "mac"

    CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype_userConnection CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype = "userConnection"

    CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype_msPdsn CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype = "msPdsn"

    CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype_mobility CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype = "mobility"

    CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype_voip CISCOTAP2MIB_Ctap2Streamtable_Ctap2Streamentry_Ctap2Streamtype = "voip"
)

// CISCOTAP2MIB_Ctap2Debugtable
// A table that contains Lawful Intercept debug messages
// generated by the implementing device. This table is used 
// by ciscoTap2MediationDebug and ciscoTap2StreamDebug 
// notifications.
// 
// An entry in this table contains a debug message which is
// regarding either a Mediation Device or a intercept stream 
// created by a Mediation Device. The Mediation device is 
// identified by cTap2DebugMediationId whose value is
// that of cTap2MediationContentId of cTapMediationEntry.
// The stream is identified by cTap2DebugMediationId and
// cTap2DebugStreamId whose values are that of 
// cTap2MediationContentId and cTap2StreamIndex of 
// the corresponding cTap2StreamEntry.
// 
// Note that cTap2DebugStreamId may be zero for an entry,
// in which case the debug message is regarding a Medation
// Device.
// 
// Entries are added to this table via cTap2DebugStatus in
// accordance with the RowStatus convention.
type CISCOTAP2MIB_Ctap2Debugtable struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // A list of the debug messages. The type is slice of
    // CISCOTAP2MIB_Ctap2Debugtable_Ctap2Debugentry.
    Ctap2Debugentry []CISCOTAP2MIB_Ctap2Debugtable_Ctap2Debugentry
}

func (ctap2Debugtable *CISCOTAP2MIB_Ctap2Debugtable) GetEntityData() *types.CommonEntityData {
    ctap2Debugtable.EntityData.YFilter = ctap2Debugtable.YFilter
    ctap2Debugtable.EntityData.YangName = "cTap2DebugTable"
    ctap2Debugtable.EntityData.BundleName = "cisco_ios_xe"
    ctap2Debugtable.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    ctap2Debugtable.EntityData.SegmentPath = "cTap2DebugTable"
    ctap2Debugtable.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Debugtable.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Debugtable.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Debugtable.EntityData.Children = make(map[string]types.YChild)
    ctap2Debugtable.EntityData.Children["cTap2DebugEntry"] = types.YChild{"Ctap2Debugentry", nil}
    for i := range ctap2Debugtable.Ctap2Debugentry {
        ctap2Debugtable.EntityData.Children[types.GetSegmentPath(&ctap2Debugtable.Ctap2Debugentry[i])] = types.YChild{"Ctap2Debugentry", &ctap2Debugtable.Ctap2Debugentry[i]}
    }
    ctap2Debugtable.EntityData.Leafs = make(map[string]types.YLeaf)
    return &(ctap2Debugtable.EntityData)
}

// CISCOTAP2MIB_Ctap2Debugtable_Ctap2Debugentry
// A list of the debug messages.
type CISCOTAP2MIB_Ctap2Debugtable_Ctap2Debugentry struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // This attribute is a key. Index to the debug table. The type is interface{}
    // with range: 1..2147483647.
    Ctap2Debugindex interface{}

    // The value of this object is that of cTap2MediationContentId identifying an
    // entry in cTap2MediationTable. Note this object may contain a value for
    // which an entry in cTap2MediationTable does not exist. This happens when
    // creation of an entry in cTap2MediationTable fails and this debug message
    // conveys more detailed information regarding the failure. The type is
    // interface{} with range: 0..4294967295.
    Ctap2Debugmediationid interface{}

    // The value of this object is that of cTap2StreamIndex of an entry in
    // cTap2StreamTable. This object along with cTap2DebugMediationId identifies
    // an entry in cTap2StreamTable. The value of this object may be zero, in
    // which this debug message is regarding a Mediation Device, but not a
    // particular stream.  Note this object may contain a value for which an 
    // entry in cTap2MediationTable does not exist. This happens  when creation of
    // an entry in cTap2StreamTable fails. The type is interface{} with range:
    // 0..4294967295.
    Ctap2Debugstreamid interface{}

    // A text string contains the debug message. The type is string.
    Ctap2Debugmessage interface{}

    // The status of this conceptual row. A row in this table is created by the
    // implementing device. A management station cannot modify any of the objects
    // in this row, except deleting the row by setting this object to 'destroy'.
    // The type is RowStatus.
    Ctap2Debugstatus interface{}
}

func (ctap2Debugentry *CISCOTAP2MIB_Ctap2Debugtable_Ctap2Debugentry) GetEntityData() *types.CommonEntityData {
    ctap2Debugentry.EntityData.YFilter = ctap2Debugentry.YFilter
    ctap2Debugentry.EntityData.YangName = "cTap2DebugEntry"
    ctap2Debugentry.EntityData.BundleName = "cisco_ios_xe"
    ctap2Debugentry.EntityData.ParentYangName = "cTap2DebugTable"
    ctap2Debugentry.EntityData.SegmentPath = "cTap2DebugEntry" + "[cTap2DebugIndex='" + fmt.Sprintf("%v", ctap2Debugentry.Ctap2Debugindex) + "']"
    ctap2Debugentry.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Debugentry.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Debugentry.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Debugentry.EntityData.Children = make(map[string]types.YChild)
    ctap2Debugentry.EntityData.Leafs = make(map[string]types.YLeaf)
    ctap2Debugentry.EntityData.Leafs["cTap2DebugIndex"] = types.YLeaf{"Ctap2Debugindex", ctap2Debugentry.Ctap2Debugindex}
    ctap2Debugentry.EntityData.Leafs["cTap2DebugMediationId"] = types.YLeaf{"Ctap2Debugmediationid", ctap2Debugentry.Ctap2Debugmediationid}
    ctap2Debugentry.EntityData.Leafs["cTap2DebugStreamId"] = types.YLeaf{"Ctap2Debugstreamid", ctap2Debugentry.Ctap2Debugstreamid}
    ctap2Debugentry.EntityData.Leafs["cTap2DebugMessage"] = types.YLeaf{"Ctap2Debugmessage", ctap2Debugentry.Ctap2Debugmessage}
    ctap2Debugentry.EntityData.Leafs["cTap2DebugStatus"] = types.YLeaf{"Ctap2Debugstatus", ctap2Debugentry.Ctap2Debugstatus}
    return &(ctap2Debugentry.EntityData)
}

// CISCOTAP2MIB_Ctap2Debugusertable
// The User Table lists information of all the users configured
// in the system who are given permission by different Mediation
// Devices to access Lawful Intercept CLIs.
// 
// This table will have dependancy on cTap2MediationTable. When
// entry in cTap2MediationTable is deleted or moved to
// 'notInService', entries corresponding cTap2MediationContentId
// in this table will be deleted.
type CISCOTAP2MIB_Ctap2Debugusertable struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // A conceptual row in the cTap2DebugUserTable. Each row represents name of
    // user on the router to whom Mediation Device with CCCid represented by
    // cTap2MediationContentId has given access to Lawful Intercept commands and
    // cTap2DebugUserTimeout represents the time when the entry will expire. The
    // type is slice of CISCOTAP2MIB_Ctap2Debugusertable_Ctap2Debuguserentry.
    Ctap2Debuguserentry []CISCOTAP2MIB_Ctap2Debugusertable_Ctap2Debuguserentry
}

func (ctap2Debugusertable *CISCOTAP2MIB_Ctap2Debugusertable) GetEntityData() *types.CommonEntityData {
    ctap2Debugusertable.EntityData.YFilter = ctap2Debugusertable.YFilter
    ctap2Debugusertable.EntityData.YangName = "cTap2DebugUserTable"
    ctap2Debugusertable.EntityData.BundleName = "cisco_ios_xe"
    ctap2Debugusertable.EntityData.ParentYangName = "CISCO-TAP2-MIB"
    ctap2Debugusertable.EntityData.SegmentPath = "cTap2DebugUserTable"
    ctap2Debugusertable.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Debugusertable.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Debugusertable.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Debugusertable.EntityData.Children = make(map[string]types.YChild)
    ctap2Debugusertable.EntityData.Children["cTap2DebugUserEntry"] = types.YChild{"Ctap2Debuguserentry", nil}
    for i := range ctap2Debugusertable.Ctap2Debuguserentry {
        ctap2Debugusertable.EntityData.Children[types.GetSegmentPath(&ctap2Debugusertable.Ctap2Debuguserentry[i])] = types.YChild{"Ctap2Debuguserentry", &ctap2Debugusertable.Ctap2Debuguserentry[i]}
    }
    ctap2Debugusertable.EntityData.Leafs = make(map[string]types.YLeaf)
    return &(ctap2Debugusertable.EntityData)
}

// CISCOTAP2MIB_Ctap2Debugusertable_Ctap2Debuguserentry
// A conceptual row in the cTap2DebugUserTable. Each row
// represents name of user on the router to whom Mediation Device
// with CCCid represented by cTap2MediationContentId has given
// access to Lawful Intercept commands and cTap2DebugUserTimeout
// represents the time when the entry will expire.
type CISCOTAP2MIB_Ctap2Debugusertable_Ctap2Debuguserentry struct {
    EntityData types.CommonEntityData
    YFilter yfilter.YFilter

    // This attribute is a key. The type is string with range: 1..2147483647.
    // Refers to
    // cisco_tap2_mib.CISCOTAP2MIB_Ctap2Mediationtable_Ctap2Mediationentry_Ctap2Mediationcontentid
    Ctap2Mediationcontentid interface{}

    // This attribute is a key. A human readable string representing the name of
    // debug user who will have access to Lawful Intercept commands. The type is
    // string with length: 1..255.
    Ctap2Debugusername interface{}

    // This object specifies the time at which the row will be removed from the
    // table by the system. The value of this object is only effective when the
    // value of corresponding instance of cTap2DebugUserStatus is 'active'. The
    // type is string.
    Ctap2Debugusertimeout interface{}

    // This object specifies the storage type of this conceptual row. If it is set
    // to 'nonVolatile', this entry can be saved into non-volatile memory. The
    // type is StorageType.
    Ctap2Debuguserstoragetype interface{}

    // The status of this conceptual row. This object manages creation,
    // modification, and deletion of rows in this table. cTap2DebugUserTimeout may
    // be modified any time even when the value of this entry rowStatus object is
    // 'active'. The type is RowStatus.
    Ctap2Debuguserstatus interface{}
}

func (ctap2Debuguserentry *CISCOTAP2MIB_Ctap2Debugusertable_Ctap2Debuguserentry) GetEntityData() *types.CommonEntityData {
    ctap2Debuguserentry.EntityData.YFilter = ctap2Debuguserentry.YFilter
    ctap2Debuguserentry.EntityData.YangName = "cTap2DebugUserEntry"
    ctap2Debuguserentry.EntityData.BundleName = "cisco_ios_xe"
    ctap2Debuguserentry.EntityData.ParentYangName = "cTap2DebugUserTable"
    ctap2Debuguserentry.EntityData.SegmentPath = "cTap2DebugUserEntry" + "[cTap2MediationContentId='" + fmt.Sprintf("%v", ctap2Debuguserentry.Ctap2Mediationcontentid) + "']" + "[cTap2DebugUserName='" + fmt.Sprintf("%v", ctap2Debuguserentry.Ctap2Debugusername) + "']"
    ctap2Debuguserentry.EntityData.CapabilitiesTable = cisco_ios_xe.GetCapabilities()
    ctap2Debuguserentry.EntityData.NamespaceTable = cisco_ios_xe.GetNamespaces()
    ctap2Debuguserentry.EntityData.BundleYangModelsLocation = cisco_ios_xe.GetModelsPath()

    ctap2Debuguserentry.EntityData.Children = make(map[string]types.YChild)
    ctap2Debuguserentry.EntityData.Leafs = make(map[string]types.YLeaf)
    ctap2Debuguserentry.EntityData.Leafs["cTap2MediationContentId"] = types.YLeaf{"Ctap2Mediationcontentid", ctap2Debuguserentry.Ctap2Mediationcontentid}
    ctap2Debuguserentry.EntityData.Leafs["cTap2DebugUserName"] = types.YLeaf{"Ctap2Debugusername", ctap2Debuguserentry.Ctap2Debugusername}
    ctap2Debuguserentry.EntityData.Leafs["cTap2DebugUserTimeout"] = types.YLeaf{"Ctap2Debugusertimeout", ctap2Debuguserentry.Ctap2Debugusertimeout}
    ctap2Debuguserentry.EntityData.Leafs["cTap2DebugUserStorageType"] = types.YLeaf{"Ctap2Debuguserstoragetype", ctap2Debuguserentry.Ctap2Debuguserstoragetype}
    ctap2Debuguserentry.EntityData.Leafs["cTap2DebugUserStatus"] = types.YLeaf{"Ctap2Debuguserstatus", ctap2Debuguserentry.Ctap2Debuguserstatus}
    return &(ctap2Debuguserentry.EntityData)
}

